import { profileSchema, type Profile } from './model.js';

export const beginMarker = '# BEGIN ALSA-VIRTUAL-TOOLS';
export const endMarker = '# END ALSA-VIRTUAL-TOOLS';
const quote = (value: string) => `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
const hwTarget = (target: string) => {
  const match = target.match(/^plughw:CARD=([A-Za-z0-9_-]+),DEV=(\d+)$/);
  if (!match) throw new Error(`Invalid hardware target: ${target}`);
  return { card: match[1] ?? '', device: match[2] ?? '' };
};

export function renderBlock(profiles: Profile[], capsPath: string): string {
  const active = profiles.filter((profile) => profile.enabled);
  const entries = active.map((raw) => {
    const p = profileSchema.parse(raw);
    const pcm =
      p.eqEnabled === false
        ? (() => {
            const target = hwTarget(p.target);
            return `pcm.${p.pcmName} {\n    type copy\n    slave.pcm ${quote(`hw:CARD=${target.card},DEV=${target.device}`)}\n    hint {\n        show on\n        description ${quote(`ALSATools Bit-perfect: ${p.displayName}`)}\n    }\n}`;
          })()
        : `ctl.${p.ctlName} {\n    type equal\n    controls ${quote(p.controlsPath)}\n    library ${quote(capsPath)}\n    module "Eq10"\n    channels ${p.channels}\n}\n\npcm.${p.internalPcmName} {\n    type equal\n    slave.pcm ${quote(p.target)}\n    controls ${quote(p.controlsPath)}\n    library ${quote(capsPath)}\n    module "Eq10"\n    channels ${p.channels}\n}\n\npcm.${p.pcmName} {\n    type plug\n    slave.pcm ${quote(p.internalPcmName)}\n    hint {\n        show on\n        description ${quote(`ALSATools Equalizer: ${p.displayName}`)}\n    }\n}`;
    return pcm;
  });
  return `${beginMarker}\n# Generated by alsa-virtual-tools. Do not edit this block manually.\n\n${entries.join('\n\n')}\n${endMarker}\n`;
}

export function replaceManagedBlock(existing: string, block: string): string {
  const start = existing.indexOf(beginMarker);
  const end = existing.indexOf(endMarker);
  if (start === -1 && end === -1)
    return existing + (existing && !existing.endsWith('\n') ? '\n' : '') + block;
  if (start < 0 || end < start)
    throw new Error('Malformed alsa-virtual-tools markers in .asoundrc');
  const after = end + endMarker.length;
  const newline = existing.slice(after).startsWith('\n') ? 1 : 0;
  return existing.slice(0, start) + block + existing.slice(after + newline);
}

export function unmanagedEqualDefinitions(content: string): string[] {
  const ownStart = content.indexOf(beginMarker);
  const ownEnd = content.indexOf(endMarker);
  const external =
    ownStart >= 0 && ownEnd >= ownStart
      ? content.slice(0, ownStart) + content.slice(ownEnd + endMarker.length)
      : content;
  return [...external.matchAll(/(?:pcm|ctl)\.([A-Za-z][A-Za-z0-9_-]*)\s*\{\s*type\s+equal/g)].map(
    (m) => m[1] ?? 'unknown',
  );
}
